spring:
  application:
    name: booking
  mongodb:
    uri: mongodb+srv://hiran:1234@cluster0.4sfue.mongodb.net/vehicle_bookings?retryWrites=true&w=majority

server:
  port: 8082

user:
  service:
    url: http://user-service:8081

vehicle:
  service:
    url: http://vehicle-service:8083