spring:
  application:
    name: booking
  mongodb:
    uri: mongodb+srv://hiran9204:1234@cluster0.4sfue.mongodb.net/?appName=Cluster0

server:
  port: 8082

user:
  service:
    url: http://user-service:8081

vehicle:
  service:
    url: http://vehicle-service:8083